language: python
python:
  - "2.7"
env:
    - PIP_DOWNLOAD_CACHE=$HOME/.pip_cache
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - "python setup.py install"
script:
  - "python runtests.py"
